---
before_install:
  # Install pandoc
  - sudo apt-get update
  - sudo apt-get -y install pandoc
  - pandoc --version

script:
  # create docs directory for pandoc output
  - mkdir docs
  # Generate reveal.js powered HTML from Markdown
  - pandoc --standalone -t revealjs -o docs/index.html presentation.md -V revealjs-url=https://revealjs.com -V theme=solarized

# Deploy to GitHub pages (see https://docs.travis-ci.com/user/deployment/pages/)
deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master